# Use a Python base image
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app


# Copy the current directory contents into the container at /app
COPY . /app


# Disable output buffering
ENV PYTHONUNBUFFERED=1
# # Install dependencies from requirements.txt
# RUN pip install --no-cache-dir -r /app/requirements.txt

# Expose the application port
EXPOSE 5000

# Command to run the Flask app
CMD ["python", "/app/dynamic_config.py"]
